#mrs_user:
#    resource: "@UserBundle/Controller/"
#    type:   annotation
mrs_user:
    resource: "@UserBundle/Resources/config/routing.yml"

app_financas:
    resource: "@MRSControleBundle/Controller/"
    type:     annotation