user_login:
  path: /login
  defaults: {_controller: UserBundle:Login:login }

user_check:
  path: /logincheck
  defaults: {_controller: UserBundle:Login:loginCheck }

user_logout:
  path: /logout
  defaults: {_controller: UserBundle:Login:logout }

user_index:
  path: /about/user/{valor}
  defaults: { _controller: UserBundle:User:getAllUser, valor: 1 }
  methods: [POST|GET]

users:
  resource: "@UserBundle/Controller/"
  type: annotation
  prefix: /admin